(define (call_py_flipscale pattern width height)
  (let* ((filelist (cadr (file-glob pattern 1))))
    (while (not (null? filelist))
      (let* ((filename (car filelist))
        (image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
        (drawable (car (gimp-image-get-active-layer image))))
        (python-fu-flipscale RUN-INTERACTIVE image drawable width height)
        (set! filelist (cdr filelist))
      )
    )
  )
)

